### ISSUE TITLE
Is it a requirement that the tray app runs on 40602 instead of 40600?

### ISSUE THREAD

**Issue by andrewxhill** [textileio/desktop#26]
Seems like it should run on 40600 unless there is a conflict on the port, is that possible?

**Comment by sanderpick** [comment]
I believe there are ways to do it well, but it might be confusing to the client user because they might have an instance of js-http pointed at the default. 

Seems like we actually want to bail on node start if the port is in use... right now an error is logged, which is not visible to tray users.

Another option is to _not_ bail on node start, but to just display the error in the UI: "unable to start API because..." or something.

**Comment by sanderpick** [comment]
But agreed, seems like it should default to 40600 like a normal peer.

**Comment by carsonfarmer** [comment]
Agreed, I think we discussed this offline. Consolidate to 40600, and throw error from tray app if ports conflict. Should be pretty easy to catch I think, and even send the error to JS land pretty easily.

**Comment by carsonfarmer** [comment]
Fixed with #29
